openapi: 3.0.3
info:
  description: Api that will measure the happyness of the teams
  title: Team happiness - Buddy program
  version: 1.0.0
servers:
- url: https://localhost:8080
tags:
- description: Everything about the teams in the Hub
  name: Teams
- description: Questions that are going to make to the teams
  name: Questions
- description: This will be use to recive user responses
  name: Survey
- description: This will be use to retrieve options of questions
  name: Option_question
paths:
  /team:
    get:
      description: Get all the teams
      operationId: getTeams
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayTeams'
          description: Successful operation
      summary: Get all the teams in the Hub
      tags:
      - Teams
      x-accepts: application/json
      x-tags:
      - tag: Teams
  /question:
    get:
      description: Get all the question
      operationId: getQuestions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayQuestions'
          description: Successful operation
      summary: Get all the questions
      tags:
      - Questions
      x-accepts: application/json
      x-tags:
      - tag: Questions
  /survey:
    post:
      description: Insert a survey data
      operationId: postSurvey
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Survey'
        description: Survey to insert in the database
        required: true
      responses:
        "201":
          description: Successful operation
      summary: Insert a surver
      tags:
      - Survey
      x-content-type: application/json
      x-accepts: application/json
      x-tags:
      - tag: Survey
  /option:
    get:
      description: Get all the options of a question
      operationId: getOption
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOptionquestion'
          description: Successful operation
      summary: Get all the options for the question
      tags:
      - Option_question
      x-accepts: application/json
      x-tags:
      - tag: Option_question
components:
  schemas:
    ArrayTeams:
      items:
        $ref: '#/components/schemas/Team'
      type: array
    Team:
      example:
        teamName: SQA
        teamId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
      properties:
        teamId:
          example: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          format: UUID
          type: string
        teamName:
          example: SQA
          type: string
      required:
      - teamId
      - teamName
      type: object
    ArrayQuestions:
      items:
        $ref: '#/components/schemas/Question'
      type: array
    Question:
      example:
        questionId: 47455c16-41ee-4622-8a75-697aacfa2466
        question: How are you feeling today?
        optionId: 47455c16-41ee-4622-8a75-697aacfa2466
        optionDTOList:
        - surveyId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          questionId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          color: orange
          optionId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          valorOption: neutral
        - surveyId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          questionId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          color: orange
          optionId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          valorOption: neutral
        questionType: traffic_light
      properties:
        optionId:
          example: 47455c16-41ee-4622-8a75-697aacfa2466
          format: UUID
          type: string
        questionId:
          example: 47455c16-41ee-4622-8a75-697aacfa2466
          format: UUID
          type: string
        questionType:
          enum:
          - traffic_light
          type: string
        question:
          example: How are you feeling today?
          type: string
        optionDTOList:
          items:
            $ref: '#/components/schemas/ArrayOptionquestion'
          type: array
      required:
      - optionDTOList
      - question
      - questionId
      - questionType
      type: object
    ArrayOptionquestion:
      example:
        surveyId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
        questionId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
        color: orange
        optionId: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
        valorOption: neutral
      properties:
        optionId:
          example: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          format: UUID
          type: string
        surveyId:
          example: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          format: UUID
          type: string
        questionId:
          example: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          format: UUID
          type: string
        valorOption:
          example: neutral
          type: string
        color:
          example: orange
          type: string
      required:
      - color
      - optionId
      - questionId
      - surveyId
      - valorOption
      type: object
    Survey:
      properties:
        surveyId:
          example: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          format: UUID
          type: string
        teamId:
          example: b2f7a764-14b5-45dd-9222-0a4a746f4f7d
          format: UUID
          type: string
      required:
      - surveyId
      - teamId
      type: object
    Answer:
      properties:
        answerId:
          example: 47455c16-41ee-4622-8a75-697aacfa2466
          format: UUID
          type: string
        surveyId:
          example: 47455c16-41ee-4622-8a75-697aacfa2466
          format: UUID
          type: string
        questionId:
          example: 47455c16-41ee-4622-8a75-697aacfa2466
          format: UUID
          type: string
      required:
      - answerId
      - questionId
      - surveyId
      type: object
